travis:
  secure:
    BINSTAR_TOKEN: a63Th3fFbTq6crKwYIz1qDUPyxbQt2HQegRwJLdBWyVcrQ/N6KAm8xqt2P/Osf81CmrhWlE5KEW/91dbCR3nBCH5KrqELWymPxObn12oD2GpWNXQQCOAwamvMrR7z1wJuw9CDd0MKZcrQaNW2DRxO1qOiAh88r6BPAbxg9zD2vPACdZmwqQdCFttfMZqvjItEuHXMPUGq8vvBYkYYKChRqwttWg7FCba8FGvoU4sR2BKhLk/ir9M/23x+wfQH0kVZCKhAif5U/ZOWue3JqkmsJhSg3+EVht+1++Nqo9rHVabGATXj7wOwWuozt+AQwHbbk3E1tnUzxaJTbz+St2BI55kGzjPo0FntCl03F6urrK4Zpvm4XeCl3p/mJpfnTrplseiblLAkDyU165Z8dyqGALYOncpu1oqI8/yNLr796jV5pGo4OfU9im3zq+yc3+ibQWnJ+Md/QrIodDMctH8vnHfhmKxRqHzZhD3UdMABv6BKhu1IaAmTz2mYWWlR6/xOCZZrDGTnGUzQ0enn7FWG5mFU9DpflP4W7mmauuY5a9KaqMdE73Yu03cSL1j7adwRGN+nhTERdaBhqdYLSaRkWX6u8qzO+1O77sW5ACRy5eHCoMMLSxfPABHbM5XRiu5KtBP0VtHM3XGV19lMpa75FLRB8jgpNOEEb7z+tjNRO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
