travis:
  secure:
    BINSTAR_TOKEN: IWiMFH47qsaSEeCcGV1J8PJPsYu3rbkSJo/QyjyLn6ODEb7ec6ULRKwlgq9klkMm+dGWwXvJi3f5S0y3oHSEAjN8l6RolF1U1z2ZDXgeDficziAEkgx0LJ5rMtfOYzbn6g/e7Nlswjp0SnNc4wbLj1yabcEShWpA8v3/H2+oeSXfhy6HzHfx1jLfOuXYNl2zCQR9cG6J92K1LZwC7Alo56VBjUeESeP5+jxeHmzoshwrVUckgevEJJs7Ub3YaqEEpiMKUSAdloAUivvmYin1s72l8oWS+JDE1s8FB4lq3O+t6S92kGAVLKkzsDOPwR6F3Ip3JFLP3hdV8ylVU7vyzLYcukkzEVMm2IzsaCqcsoodK1NLfvsOWsKZBGZ0UkA7PiZUiE5qrY198mS2JtGuuRBjgWgNHsnWi5fBSDyLC6/0uAnscVPpcq1g4w49E4P5e3HJcqsZJw1v2qERffE0ON6AGLqj00Xt9uBByeaiCmgxYFvtFvOW37LRYqerdAJ50U0jPfmZDvB19Z5nCbtRHCtMbbeGhjtWjhTPVPSGiG0xqrbLIsTvv/m3UdMrUWw7L2iseV7ZZoT8XLyqI+v9JTC1kv7P0jRY6/mWadKpdMCL/KazySqp4/SFlEiSPa1F6Qx85Q7DZe1++h/1ojBJhYLEVBErcW+h/EC+cXo5vN4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
