travis:
  secure:
    BINSTAR_TOKEN: dD/m44dYM/DAJ0YKcu9/KURX0JYMJ0lQq8qN6FP5yvxtDbzn9u40+1QZUUaXj994J81TLNRh9981Q2c2SkKdeAcOzbWdbpWJ17NoGrp3om1ouAqiv2w3BdHPl+Ie85kSCgeGcNoGBCZVLOVzq/k2Ql0yWrbdRK4R31wjGidjhIrYe3vqSUTFhBp1So/I/vWdu/gJZQP1lRPJ6tGAIVbSxDSJZFhHUrAQoLdcCDFJ5mhkuEagDhVyIWq85ycFLzB08lkyDIQKc4xAuM7h1gmO8trbSy4qW0+zxfBhjaMcF53HgicwBZufW7+Kbx6TJ7v/5d339J+CxUpg9PQTG+9e0mFVFRn+ATmwBO667riblL1strwyV8hupRor2UMTAwcgSFlLs3Pfe1M+oLAEipmNgCkj0TM7jXBHJeP8t8FT0nbX6sB2XNyi9SmICA0TH340iL7to/IvaziZzUfRH5LOf7ZP+bMEIE4Hi8TcMR36FXegGBFjJX8Q75oNdZcUnLcV8IcMGySyHJKlNwZYEIuIUtTb6XfypeYdWjX3siijGKETmxNJfe7vXcpWZpxbVtkJaloMfcyVoqV3jfnTQimEi5A2YYeSsBUAmK/TMoQGQhQkdQSsBMTRtwff6skRJnebgnSr28tiiRMhThhQ3Td1HCgL/yFo1Py+qC6v9YI9VkA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
