travis:
  secure:
    BINSTAR_TOKEN: gUEdjhfBf75SiTlFITyG2RBihiiBXd+KTj8XQWKrt3F8YH/rJPhPvEvj6WyBgDgJaJ9039v5A5Uhe89rI6pJRcLPRVLCpPyHsS5R1OnPfF1qyvyyDi28F6TCeYHyva3gjMHYhQsgWYG4LfqFHxiHhR9UThx7RsnOV5sqyTH6jojOIWHLwG3kTc1epJa3qPCfvkMlRm508ikMpSXy4WJdQt8b94N+M4x+Kup+pGlUG/BNwfxIrFqUC8jVLYqoc5xjlvUfK5ZR20TwNH2frERS4uCUcvVNLR6RL2x+WC2mvpzL4cbTtI4GjhnAY8GMyEnTcg9o4s+hSZXIhjpzj2qM5L+/17kYuGhdu+VrHTP2WQ0CWhM/7KrVSDJ8IFxTfOjrWcu7ksAsNVZ/1p9iRsDDNU5qAs7Ww/uYmreprDvyVrDYR5mZxccnno291LIq1PeAttMfgO+FN+tYloRk+NbLT08VQeHoRQEkX5qV8dYQXryTVaXJizthsoijN3YbNPWHSvDFeI0Xlv8bcjZT96sqL8RWVSKn0vHsSPiZac3Yjl+x3QhVuzslfmg7c7UfbbH2quJpNRlQKT/9wPr4W1nRQQXn0zjJDYJF3JyfYDxe+KTUec6Dh7qUriMxwBfU2QIYQVPbPO1N0NlI4SIqyWbLbnfpkaHuTeQrkt/h6txEOdo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
